[project]
name = "threadalchemy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Paul", email = "pr@opale.pro" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.20.0",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.142.2",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.2",
]

[entrypoint]
entrypoint = "app.main:app"

[project.scripts]
app = "app:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=9.17.1",
    "ruff>=0.16.10",
]

[tool.ruff]
line-length = 100
target-version = "py314"  # adapte à ta version

[tool.ruff.lint]
select = [
  "E", "F",   # pycodestyle + pyflakes (erreurs de base)
  "I",        # tri des imports
  "UP",       # syntaxe Python moderne
  "B",        # bugbear (pièges courants)
  "SIM",      # simplifications
  "FAST",     # règles spécifiques FastAPI
]
